// export const  = {
//   skill
// }

// const getRange = (min: number, max: number, step?: number = 1) =>
//   Array.from(new Array(max > min ? Math.ceil((max - min) / step) : Math.ceil((min - max) / step)), (x, i) =>
//     max > min ? i * step + min : min - i * step
//   ).join(' | ');

// explained at https://rares.uk/typescript-unextend-interface/
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export const MAX_VALUE = {
  x: 6,
  y: 48,
};

export type NodeTypeType = 'stats' | 'skill' | 'special';

export type NODEType = {
  id: number;
  x: number;
  y: number;
  type: NodeTypeType;
  point: 1 | 2 | 3 | 4 | 5;
  name: string;
  value?: number;
  description?: string;
  prevNodesIndexes: number[];
};

export type NODESType = NODEType[];

export const NODES: NODESType = [
  {
    id: 0,
    x: 2,
    y: 0,
    type: 'stats',
    point: 1,
    name: '威',
    value: 5,
    prevNodesIndexes: [],
  },
  {
    id: 1,
    x: 4,
    y: 2,
    type: 'stats',
    point: 2,
    name: '耐',
    value: 5,
    prevNodesIndexes: [0],
  },
  {
    id: 2,
    x: 5,
    y: 3,
    type: 'stats',
    point: 2,
    name: '秘',
    value: 5,
    prevNodesIndexes: [1],
  },
  {
    id: 3,
    x: 2,
    y: 4,
    type: 'stats',
    point: 2,
    name: '运',
    value: 5,
    prevNodesIndexes: [1],
  },
  {
    id: 4,
    x: 1,
    y: 5,
    type: 'stats',
    point: 3,
    name: '全属性',
    value: 3,
    prevNodesIndexes: [3],
  },
  {
    id: 5,
    x: 3,
    y: 5,
    type: 'stats',
    point: 2,
    name: '敏',
    value: 5,
    prevNodesIndexes: [2, 3],
  },
  {
    id: 6,
    x: 3,
    y: 7,
    type: 'stats',
    point: 3,
    name: '一转',
    value: 2,
    prevNodesIndexes: [5],
  },
  {
    id: 7,
    x: 5,
    y: 7,
    type: 'stats',
    point: 3,
    name: '一转',
    value: 2,
    prevNodesIndexes: [2],
  },
  {
    id: 8,
    x: 6,
    y: 8,
    type: 'stats',
    point: 3,
    name: '运',
    value: 5,
    prevNodesIndexes: [7],
  },
  {
    id: 9,
    x: 1,
    y: 9,
    type: 'stats',
    point: 3,
    name: '耐',
    value: 5,
    prevNodesIndexes: [6],
  },
  {
    id: 10,
    x: 3,
    y: 9,
    type: 'stats',
    point: 3,
    name: '敏',
    value: 5,
    prevNodesIndexes: [6],
  },
  {
    id: 11,
    x: 5,
    y: 9,
    type: 'stats',
    point: 3,
    name: '威',
    value: 5,
    prevNodesIndexes: [7],
  },
  {
    id: 12,
    x: 2,
    y: 10,
    type: 'stats',
    point: 3,
    name: '普攻',
    value: 0.07,
    prevNodesIndexes: [9, 10],
  },
  {
    id: 13,
    x: 4,
    y: 10,
    type: 'stats',
    point: 3,
    name: '腕力',
    value: 0.5,
    prevNodesIndexes: [11],
  },
  {
    id: 14,
    x: 6,
    y: 10,
    type: 'stats',
    point: 3,
    name: '秘',
    value: 5,
    prevNodesIndexes: [8],
  },
  {
    id: 15,
    x: 1,
    y: 13,
    type: 'special',
    point: 4,
    name: '燃烧间隔-50%',
    prevNodesIndexes: [9],
  },
  {
    id: 16,
    x: 3,
    y: 13,
    type: 'stats',
    point: 3,
    name: '二转',
    value: 2,
    prevNodesIndexes: [14],
  },
  {
    id: 17,
    x: 2,
    y: 14,
    type: 'stats',
    point: 3,
    name: '全抗性',
    value: 0.04,
    prevNodesIndexes: [],
  },
  {
    id: 18,
    x: 1,
    y: 15,
    type: 'stats',
    point: 3,
    name: '二转',
    value: 2,
    prevNodesIndexes: [15, 17],
  },
  {
    id: 19,
    x: 3,
    y: 15,
    type: 'stats',
    point: 3,
    name: '全属性',
    value: 3,
    prevNodesIndexes: [16],
  },
  {
    id: 20,
    x: 0,
    y: 16,
    type: 'skill',
    point: 5,
    name: '生命绽放',
    description: '使角色持续5秒每秒恢复生命，持续时间内受到的伤害降低40%。\n每秒恢复：角色攻击57.4%点生命值。',
    prevNodesIndexes: [18],
  },
  {
    id: 21,
    x: 2,
    y: 16,
    type: 'stats',
    point: 3,
    name: '暴击率',
    value: 0.05,
    prevNodesIndexes: [17, 19],
  },
  {
    id: 22,
    x: 1,
    y: 17,
    type: 'stats',
    point: 3,
    name: '威',
    value: 5,
    prevNodesIndexes: [20],
  },
  {
    id: 23,
    x: 5,
    y: 17,
    type: 'stats',
    point: 3,
    name: '一转',
    value: 2,
    prevNodesIndexes: [],
  },
  {
    id: 24,
    x: 2,
    y: 18,
    type: 'stats',
    point: 3,
    name: '秘',
    value: 5,
    prevNodesIndexes: [22],
  },
  {
    id: 25,
    x: 6,
    y: 18,
    type: 'special',
    point: 4,
    name: '中毒效果翻倍',
    prevNodesIndexes: [],
  },
  {
    id: 26,
    x: 1,
    y: 19,
    type: 'skill',
    point: 5,
    name: '灵魂射线',
    description: '随机对多个目标进行攻击，造成暗属性伤害，距离越远攻击目标越多。\n暗属性伤害：主手基础伤害205.0%+315点',
    prevNodesIndexes: [],
  },
  {
    id: 27,
    x: 5,
    y: 19,
    type: 'stats',
    point: 3,
    name: '敏',
    value: 5,
    prevNodesIndexes: [21, 23, 25],
  },
  {
    id: 28,
    x: 0,
    y: 20,
    type: 'stats',
    point: 3,
    name: '暗伤',
    value: 0.05,
    prevNodesIndexes: [26],
  },
  {
    id: 29,
    x: 2,
    y: 20,
    type: 'stats',
    point: 3,
    name: '全属性',
    value: 3,
    prevNodesIndexes: [24, 26],
  },
  {
    id: 30,
    x: 1,
    y: 21,
    type: 'stats',
    point: 3,
    name: '全伤',
    value: 0.05,
    prevNodesIndexes: [28, 29],
  },
  {
    id: 31,
    x: 3,
    y: 21,
    type: 'stats',
    point: 3,
    name: '运',
    value: 5,
    prevNodesIndexes: [29],
  },
  {
    id: 32,
    x: 5,
    y: 21,
    type: 'skill',
    point: 5,
    name: '混元盾',
    description: '角色立即获得护盾，还将获得1层圣盾，圣盾可抵挡1次攻击。\n护盾：相当于生命上限的8.6%。',
    prevNodesIndexes: [27],
  },
  {
    id: 33,
    x: 4,
    y: 22,
    type: 'stats',
    point: 3,
    name: '生命吸取',
    value: 0.04,
    prevNodesIndexes: [31],
  },
  {
    id: 34,
    x: 1,
    y: 23,
    type: 'stats',
    point: 3,
    name: '攻速',
    value: 0.1,
    prevNodesIndexes: [30],
  },
  {
    id: 35,
    x: 3,
    y: 23,
    type: 'stats',
    point: 3,
    name: '普攻',
    value: 0.07,
    prevNodesIndexes: [33],
  },
  {
    id: 36,
    x: 5,
    y: 23,
    type: 'stats',
    point: 3,
    name: '耐',
    value: 5,
    prevNodesIndexes: [32, 33],
  },
  {
    id: 37,
    x: 0,
    y: 24,
    type: 'special',
    point: 4,
    name: '流血效果翻倍',
    prevNodesIndexes: [34],
  },
  {
    id: 38,
    x: 4,
    y: 24,
    type: 'stats',
    point: 3,
    name: '格挡率',
    value: 0.05,
    prevNodesIndexes: [35, 36],
  },
  {
    id: 39,
    x: 6,
    y: 24,
    type: 'stats',
    point: 3,
    name: '二转',
    value: 2,
    prevNodesIndexes: [36],
  },
  {
    id: 40,
    x: 1,
    y: 25,
    type: 'stats',
    point: 3,
    name: '火伤',
    value: 0.05,
    prevNodesIndexes: [34],
  },
  {
    id: 41,
    x: 0,
    y: 26,
    type: 'stats',
    point: 3,
    name: '物伤',
    value: 0.05,
    prevNodesIndexes: [37],
  },
  {
    id: 42,
    x: 2,
    y: 26,
    type: 'stats',
    point: 3,
    name: '生命',
    value: 0.05,
    prevNodesIndexes: [40],
  },
  {
    id: 43,
    x: 4,
    y: 26,
    type: 'skill',
    point: 5,
    name: '超重击',
    description: '对3目标进行攻击，造成物理伤害；超重击冷却时间受主武器影响。\n物理伤害：主手基础伤害133.3%+205点。',
    prevNodesIndexes: [38],
  },
  {
    id: 44,
    x: 6,
    y: 26,
    type: 'skill',
    point: 5,
    name: '水元素',
    description: '身前召唤，水元素普攻对单体造成冰属性伤害。\n冰属性伤害：自身基础伤害307.5%+473点。',
    prevNodesIndexes: [],
  },
  {
    id: 45,
    x: 1,
    y: 27,
    type: 'skill',
    point: 5,
    name: '天体陨落',
    description:
      '触发陨石效果：每波随机2个目标降下流星，1秒内总计4波，每颗流星造成或属性伤害。\n火属性伤害：主手基础伤害153.8%+236点。',
    prevNodesIndexes: [41, 42],
  },
  {
    id: 46,
    x: 2,
    y: 28,
    type: 'stats',
    point: 3,
    name: '三转',
    value: 2,
    prevNodesIndexes: [45],
  },
  {
    id: 47,
    x: 4,
    y: 28,
    type: 'stats',
    point: 3,
    name: '攻击|召唤增幅',
    value: 0.05,
    prevNodesIndexes: [43],
  },
  {
    id: 48,
    x: 6,
    y: 28,
    type: 'stats',
    point: 3,
    name: '暴击效果',
    value: 0.1,
    prevNodesIndexes: [44],
  },
  {
    id: 49,
    x: 3,
    y: 29,
    type: 'skill',
    point: 5,
    name: '胜利鼓舞',
    description: '战斗中任意敌方目标重伤后，恢复角色生命。\n恢复：5.5%的生命。',
    prevNodesIndexes: [46, 47],
  },
  {
    id: 50,
    x: 5,
    y: 29,
    type: 'stats',
    point: 3,
    name: '三转',
    value: 2,
    prevNodesIndexes: [47, 48],
  },
  {
    id: 51,
    x: 4,
    y: 30,
    type: 'stats',
    point: 3,
    name: '光伤',
    value: 0.05,
    prevNodesIndexes: [49, 50],
  },
  {
    id: 52,
    x: 1,
    y: 31,
    type: 'stats',
    point: 3,
    name: '耐',
    value: 5,
    prevNodesIndexes: [49],
  },
  {
    id: 53,
    x: 3,
    y: 31,
    type: 'stats',
    point: 4,
    name: '全抗',
    value: 0.08,
    prevNodesIndexes: [],
  },
  {
    id: 54,
    x: 5,
    y: 31,
    type: 'stats',
    point: 3,
    name: '敏',
    value: 5,
    prevNodesIndexes: [50],
  },
  {
    id: 55,
    x: 0,
    y: 32,
    type: 'stats',
    point: 3,
    name: '冰伤',
    value: 0.05,
    prevNodesIndexes: [52],
  },
  {
    id: 56,
    x: 4,
    y: 32,
    type: 'stats',
    point: 3,
    name: '护甲',
    value: 0.05,
    prevNodesIndexes: [53, 54],
  },
  {
    id: 57,
    x: 1,
    y: 33,
    type: 'skill',
    point: 5,
    name: '链钩',
    description:
      '对2目标进行攻击，偷袭造成物理伤害，拉近距离3，是目标附带1层流血。\n物理伤害：主手基础伤害184.5%+284点。',
    prevNodesIndexes: [52, 55],
  },
  {
    id: 58,
    x: 3,
    y: 33,
    type: 'skill',
    point: 5,
    name: '净世之光',
    description: '对敌方全体进行攻击，造成光属性伤害。\n光属性伤害：主手基础伤害307.5%+473点。',
    prevNodesIndexes: [],
  },
  {
    id: 59,
    x: 5,
    y: 33,
    type: 'stats',
    point: 3,
    name: '威',
    value: 5,
    prevNodesIndexes: [],
  },
  {
    id: 60,
    x: 2,
    y: 34,
    type: 'stats',
    point: 3,
    name: '光伤|光抗',
    value: 0.05,
    prevNodesIndexes: [58],
  },
  {
    id: 61,
    x: 4,
    y: 34,
    type: 'stats',
    point: 3,
    name: '三转',
    value: 2,
    prevNodesIndexes: [59],
  },
  {
    id: 62,
    x: 6,
    y: 34,
    type: 'stats',
    point: 4,
    name: '随从攻速',
    value: 0.1,
    prevNodesIndexes: [48, 59],
  },
  {
    id: 63,
    x: 1,
    y: 35,
    type: 'stats',
    point: 3,
    name: '物伤|物抗',
    value: 0.05,
    prevNodesIndexes: [57],
  },
  {
    id: 64,
    x: 3,
    y: 35,
    type: 'stats',
    point: 4,
    name: '绝闪',
    value: 0.08,
    prevNodesIndexes: [60, 61],
  },
  {
    id: 65,
    x: 0,
    y: 36,
    type: 'stats',
    point: 3,
    name: '四转',
    value: 2,
    prevNodesIndexes: [63],
  },
  {
    id: 66,
    x: 2,
    y: 36,
    type: 'stats',
    point: 3,
    name: '全属性',
    value: 3,
    prevNodesIndexes: [64],
  },
  {
    id: 67,
    x: 6,
    y: 36,
    type: 'stats',
    point: 3,
    name: '秘',
    value: 5,
    prevNodesIndexes: [62],
  },
  {
    id: 68,
    x: 1,
    y: 37,
    type: 'stats',
    point: 4,
    name: '暴击率|暴击效果', // 5% 10%
    value: 0.05,
    prevNodesIndexes: [63],
  },
  {
    id: 69,
    x: 5,
    y: 37,
    type: 'stats',
    point: 3,
    name: '四转',
    value: 2,
    prevNodesIndexes: [67],
  },
  {
    id: 70,
    x: 2,
    y: 38,
    type: 'stats',
    point: 3,
    name: '冰伤|冰抗',
    value: 0.05,
    prevNodesIndexes: [66],
  },
  {
    id: 71,
    x: 4,
    y: 38,
    type: 'stats',
    point: 3,
    name: '威',
    value: 5,
    prevNodesIndexes: [69],
  },
  {
    id: 72,
    x: 6,
    y: 38,
    type: 'stats',
    point: 3,
    name: '暗伤|暗抗',
    value: 0.05,
    prevNodesIndexes: [67],
  },
  {
    id: 73,
    x: 3,
    y: 39,
    type: 'stats',
    point: 4,
    name: '生命吸取|全伤',
    value: 0.04,
    prevNodesIndexes: [70, 71],
  },
  {
    id: 74,
    x: 5,
    y: 39,
    type: 'skill',
    point: 5,
    name: '土元素',
    description: '身后召唤，土元素普攻对单体造成物理伤害，击退距离2.\n物理伤害：土元素基础伤害422.3%+649点。',
    prevNodesIndexes: [],
  },
  {
    id: 75,
    x: 0,
    y: 40,
    type: 'stats',
    point: 3,
    name: '运',
    value: 5,
    prevNodesIndexes: [65, 70],
  },
  {
    id: 76,
    x: 6,
    y: 40,
    type: 'stats',
    point: 3,
    name: '耐',
    value: 5,
    prevNodesIndexes: [72, 74],
  },
  {
    id: 77,
    x: 1,
    y: 41,
    type: 'skill',
    point: 5,
    name: '轮回眼',
    description: '间隔一段时间，复制前一个角色使用的技能。\n间隔时间：34秒。',
    prevNodesIndexes: [75],
  },
  {
    id: 78,
    x: 3,
    y: 41,
    type: 'stats',
    point: 3,
    name: '火伤|火炕',
    value: 0.05,
    prevNodesIndexes: [73],
  },
  {
    id: 79,
    x: 5,
    y: 41,
    type: 'stats',
    point: 3,
    name: '秘',
    value: 5,
    prevNodesIndexes: [],
  },
  {
    id: 80,
    x: 4,
    y: 42,
    type: 'stats',
    point: 4,
    name: '全属性|格挡率', // +3 10%
    value: 0.1,
    prevNodesIndexes: [78, 79],
  },
  {
    id: 81,
    x: 6,
    y: 42,
    type: 'skill',
    point: 5,
    name: '共生',
    description: '友方有任意随从存活时，则角色受到的伤害降低。\n伤害降低：11.0%。',
    prevNodesIndexes: [79],
  },
  {
    id: 82,
    x: 1,
    y: 43,
    type: 'stats',
    point: 4,
    name: '生命吸取',
    value: 0.04,
    prevNodesIndexes: [78],
  },
  {
    id: 83,
    x: 3,
    y: 43,
    type: 'stats',
    point: 3,
    name: '敏',
    value: 5,
    prevNodesIndexes: [78],
  },
  {
    id: 84,
    x: 5,
    y: 43,
    type: 'stats',
    point: 3,
    name: '运',
    value: 5,
    prevNodesIndexes: [80],
  },
  {
    id: 85,
    x: 2,
    y: 44,
    type: 'stats',
    point: 4,
    name: '格挡率|格挡效果', // +5% +10%
    value: 0.05,
    prevNodesIndexes: [82, 83],
  },
  {
    id: 86,
    x: 1,
    y: 45,
    type: 'skill',
    point: 5,
    name: '风息',
    description:
      '角色武器普攻有20%的概率触发风息效果：对目标造成真实伤害，手角色普攻伤害加成影响。\n真实伤害：主手攻击34.1%+96点。',
    prevNodesIndexes: [82],
  },
  {
    id: 87,
    x: 3,
    y: 45,
    type: 'skill',
    point: 5,
    name: '技能振幅',
    description: '角色每次使用攻击技能后，使角色伤害提高1.5%，可叠加。\n叠加次数：11次。',
    prevNodesIndexes: [84],
  },
  {
    id: 88,
    x: 5,
    y: 45,
    type: 'stats',
    point: 4,
    name: '冷却恢复',
    value: 0.08,
    prevNodesIndexes: [84],
  },
  {
    id: 89,
    x: 4,
    y: 46,
    type: 'stats',
    point: 3,
    name: '四转',
    value: 2,
    prevNodesIndexes: [87, 88],
  },
];
