import { NODESType } from './types';

// const getRange = (min: number, max: number, step?: number = 1) =>
//   Array.from(new Array(max > min ? Math.ceil((max - min) / step) : Math.ceil((min - max) / step)), (x, i) =>
//     max > min ? i * step + min : min - i * step
//   ).join(' | ');

export const MAX_VALUE = {
  x: 6,
  y: 48,
};

export const NODES: NODESType = [
  {
    id: 0,
    x: 2,
    y: 0,
    points: 1,
    perks: [{ name: 'power', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [],
  },
  {
    id: 1,
    x: 4,
    y: 2,
    points: 2,
    perks: [{ name: 'endurance', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [0],
  },
  {
    id: 2,
    x: 5,
    y: 3,
    points: 2,
    perks: [{ name: 'wisdom', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [1],
  },
  {
    id: 3,
    x: 2,
    y: 4,
    points: 2,
    perks: [{ name: 'luck', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [1],
  },
  {
    id: 4,
    x: 1,
    y: 5,
    points: 3,
    perks: [
      {
        name: 'allStats',
        type: 'baseStats',
        fullNameList: ['power', 'wisdom', 'luck', 'endurance', 'agility'],
        value: 3,
      },
    ],
    prevNodesIndexes: [3],
  },
  {
    id: 5,
    x: 3,
    y: 5,
    points: 2,
    perks: [{ name: 'agility', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [2, 3],
  },
  {
    id: 6,
    x: 3,
    y: 7,
    points: 3,
    perks: [{ name: 'beginnerSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [5],
  },
  {
    id: 7,
    x: 5,
    y: 7,
    points: 3,
    perks: [{ name: 'beginnerSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [2],
  },
  {
    id: 8,
    x: 6,
    y: 8,
    points: 3,
    perks: [{ name: 'luck', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [7],
  },
  {
    id: 9,
    x: 1,
    y: 9,
    points: 3,
    perks: [{ name: 'endurance', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [6],
  },
  {
    id: 10,
    x: 3,
    y: 9,
    points: 3,
    perks: [{ name: 'agility', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [6],
  },
  {
    id: 11,
    x: 5,
    y: 9,
    points: 3,
    perks: [{ name: 'power', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [7],
  },
  {
    id: 12,
    x: 2,
    y: 10,
    points: 3,
    perks: [{ name: 'normalAttack', type: 'offensiveStats', value: 0.07 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [9, 10],
  },
  {
    id: 13,
    x: 4,
    y: 10,
    points: 3,
    perks: [{ name: 'strength', type: 'offensiveStats', value: 0.5 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [11],
  },
  {
    id: 14,
    x: 6,
    y: 10,
    points: 3,
    perks: [{ name: 'wisdom', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [8],
  },
  {
    id: 15,
    x: 1,
    y: 13,
    points: 4,
    perks: [{ name: 'burnSpeed', type: 'special' }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [9],
  },
  {
    id: 16,
    x: 3,
    y: 13,
    points: 3,
    perks: [{ name: 'intermediateSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [14],
  },
  {
    id: 17,
    x: 2,
    y: 14,
    points: 3,
    perks: [
      {
        name: 'allResistance',
        type: 'defensiveStats',
        fullNameList: ['physicalResistance', 'fireResistance', 'iceResistance', 'lightResistance', 'darkResistance'],
        value: 0.04,
      },
    ],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [],
  },
  {
    id: 18,
    x: 1,
    y: 15,
    points: 3,
    perks: [{ name: 'intermediateSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [15, 17],
  },
  {
    id: 19,
    x: 3,
    y: 15,
    points: 3,
    perks: [
      {
        name: 'allStats',
        type: 'baseStats',
        fullNameList: ['power', 'wisdom', 'luck', 'endurance', 'agility'],
        value: 3,
      },
    ],
    prevNodesIndexes: [16],
  },
  {
    id: 20,
    x: 0,
    y: 16,
    points: 5,
    perks: [
      {
        name: 'bloomOfLife',
        type: 'skills',
        description: 'bloomOfLifeDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [18],
  },
  {
    id: 21,
    x: 2,
    y: 16,
    points: 3,
    perks: [{ name: 'critChance', type: 'offensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [17, 19],
  },
  {
    id: 22,
    x: 1,
    y: 17,
    points: 3,
    perks: [{ name: 'power', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [20],
  },
  {
    id: 23,
    x: 5,
    y: 17,
    points: 3,
    perks: [{ name: 'beginnerSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [],
  },
  {
    id: 24,
    x: 2,
    y: 18,
    points: 3,
    perks: [{ name: 'wisdom', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [22],
  },
  {
    id: 25,
    x: 6,
    y: 18,
    points: 4,
    perks: [{ name: 'poisonDamage', type: 'special' }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [],
  },
  {
    id: 26,
    x: 1,
    y: 19,
    points: 5,
    perks: [
      {
        name: 'spiritRay',
        type: 'skills',
        description: 'spiritRayDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [],
  },
  {
    id: 27,
    x: 5,
    y: 19,
    points: 3,
    perks: [{ name: 'agility', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [21, 23, 25],
  },
  {
    id: 28,
    x: 0,
    y: 20,
    points: 3,
    perks: [{ name: 'darkDamage', type: 'offensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [26],
  },
  {
    id: 29,
    x: 2,
    y: 20,
    points: 3,
    perks: [
      {
        name: 'allStats',
        type: 'baseStats',
        fullNameList: ['power', 'wisdom', 'luck', 'endurance', 'agility'],
        value: 3,
      },
    ],
    prevNodesIndexes: [24, 26],
  },
  {
    id: 30,
    x: 1,
    y: 21,
    points: 3,
    perks: [
      {
        name: 'allDamage',
        type: 'offensiveStats',
        fullNameList: ['physicalDamage', 'fireDamage', 'iceDamage', 'lightDamage', 'darkDamage'],
        value: 0.05,
      },
    ],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [28, 29],
  },
  {
    id: 31,
    x: 3,
    y: 21,
    points: 3,
    perks: [{ name: 'luck', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [29],
  },
  {
    id: 32,
    x: 5,
    y: 21,
    points: 5,
    perks: [
      {
        name: 'shieldOfChaos',
        type: 'skills',
        description: 'shieldOfChaosDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [27],
  },
  {
    id: 33,
    x: 4,
    y: 22,
    points: 3,
    perks: [{ name: 'lifesteal', type: 'defensiveStats', value: 0.04 }],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [31],
  },
  {
    id: 34,
    x: 1,
    y: 23,
    points: 3,
    perks: [{ name: 'attackSpeed', type: 'offensiveStats', value: 0.1 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [30],
  },
  {
    id: 35,
    x: 3,
    y: 23,
    points: 3,
    perks: [{ name: 'normalAttack', type: 'offensiveStats', value: 0.07 }],
    prevNodesIndexes: [33],
  },
  {
    id: 36,
    x: 5,
    y: 23,
    points: 3,
    perks: [{ name: 'endurance', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [32, 33],
  },
  {
    id: 37,
    x: 0,
    y: 24,
    points: 4,
    perks: [{ name: 'bleedDamage', type: 'special' }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [34],
  },
  {
    id: 38,
    x: 4,
    y: 24,
    points: 3,
    perks: [{ name: 'blockChance', type: 'defensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [35, 36],
  },
  {
    id: 39,
    x: 6,
    y: 24,
    points: 3,
    perks: [{ name: 'intermediateSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [36],
  },
  {
    id: 40,
    x: 1,
    y: 25,
    points: 3,
    perks: [{ name: 'fireDamage', type: 'offensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [34],
  },
  {
    id: 41,
    x: 0,
    y: 26,
    points: 3,
    perks: [{ name: 'physicalDamage', type: 'offensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [37],
  },
  {
    id: 42,
    x: 2,
    y: 26,
    points: 3,
    perks: [{ name: 'healthPoint', type: 'defensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [40],
  },
  {
    id: 43,
    x: 4,
    y: 26,
    points: 5,
    perks: [
      {
        name: 'deadlyCrush',
        type: 'skills',
        description: 'deadlyCrushDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [38],
  },
  {
    id: 44,
    x: 6,
    y: 26,
    points: 5,
    perks: [
      {
        name: 'waterElement',
        type: 'skills',
        description: 'waterElementDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [],
  },
  {
    id: 45,
    x: 1,
    y: 27,
    points: 5,
    perks: [
      {
        name: 'celestialStorm',
        type: 'skills',
        description: 'celestialStormDescription',
      },
    ],

    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [41, 42],
  },
  {
    id: 46,
    x: 2,
    y: 28,
    points: 3,
    perks: [{ name: 'advancedSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [45],
  },
  {
    id: 47,
    x: 4,
    y: 28,
    points: 3,
    perks: [
      { name: 'attack', type: 'offensiveStats', value: 0.05 },
      { name: 'summonBoost', type: 'offensiveStats', value: 0.05 },
    ],
    prevNodesIndexes: [43],
    additionalSearchKeywords: 'offense',
  },
  {
    id: 48,
    x: 6,
    y: 28,
    points: 3,
    perks: [{ name: 'critEffect', type: 'offensiveStats', value: 0.1 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [44],
  },
  {
    id: 49,
    x: 3,
    y: 29,
    points: 5,
    perks: [
      {
        name: 'emboldened',
        type: 'skills',
        description: 'emboldenedDescription',
      },
    ],
    additionalSearchKeywords: 'passiveSkill',
    prevNodesIndexes: [46, 47],
  },
  {
    id: 50,
    x: 5,
    y: 29,
    points: 3,
    perks: [{ name: 'advancedSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [47, 48],
  },
  {
    id: 51,
    x: 4,
    y: 30,
    points: 3,
    perks: [{ name: 'lightDamage', type: 'offensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [49, 50],
  },
  {
    id: 52,
    x: 1,
    y: 31,
    points: 3,
    perks: [{ name: 'endurance', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [49],
  },
  {
    id: 53,
    x: 3,
    y: 31,
    points: 4,
    perks: [
      {
        name: 'allResistance',
        type: 'defensiveStats',
        fullNameList: ['physicalResistance', 'fireResistance', 'iceResistance', 'lightResistance', 'darkResistance'],
        value: 0.08,
      },
    ],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [],
  },
  {
    id: 54,
    x: 5,
    y: 31,
    points: 3,
    perks: [{ name: 'agility', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [50],
  },
  {
    id: 55,
    x: 0,
    y: 32,
    points: 3,
    perks: [{ name: 'iceDamage', type: 'offensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [52],
  },
  {
    id: 56,
    x: 4,
    y: 32,
    points: 3,
    perks: [{ name: 'armor', type: 'defensiveStats', value: 0.05 }],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [53, 54],
  },
  {
    id: 57,
    x: 1,
    y: 33,
    points: 5,
    perks: [
      {
        name: 'chainHook',
        type: 'skills',
        description: 'chainHookDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [52, 55],
  },
  {
    id: 58,
    x: 3,
    y: 33,
    points: 5,
    perks: [
      {
        name: 'purification',
        type: 'skills',
        description: 'purificationDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [],
  },
  {
    id: 59,
    x: 5,
    y: 33,
    points: 3,
    perks: [{ name: 'power', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [],
  },
  {
    id: 60,
    x: 2,
    y: 34,
    points: 3,
    perks: [
      { name: 'lightDamage', type: 'offensiveStats', value: 0.05 },
      { name: 'lightResistance', type: 'defensiveStats', value: 0.05 },
    ],
    additionalSearchKeywords: 'offenseDefense',
    prevNodesIndexes: [58],
  },
  {
    id: 61,
    x: 4,
    y: 34,
    points: 3,
    perks: [{ name: 'advancedSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [59],
  },
  {
    id: 62,
    x: 6,
    y: 34,
    points: 4,
    perks: [{ name: 'minionAttackSpeed', type: 'offensiveStats', value: 0.1 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [48, 59],
  },
  {
    id: 63,
    x: 1,
    y: 35,
    points: 3,
    perks: [
      { name: 'physicalDamage', type: 'offensiveStats', value: 0.05 },
      { name: 'physicalResistance', type: 'defensiveStats', value: 0.05 },
    ],
    additionalSearchKeywords: 'offenseDefense',
    prevNodesIndexes: [57],
  },
  {
    id: 64,
    x: 3,
    y: 35,
    points: 4,
    perks: [{ name: 'dodge', type: 'defensiveStats', value: 0.08 }],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [60, 61],
  },
  {
    id: 65,
    x: 0,
    y: 36,
    points: 3,
    perks: [{ name: 'masterSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [63],
  },
  {
    id: 66,
    x: 2,
    y: 36,
    points: 3,
    perks: [
      {
        name: 'allStats',
        type: 'baseStats',
        fullNameList: ['power', 'wisdom', 'luck', 'endurance', 'agility'],
        value: 3,
      },
    ],
    prevNodesIndexes: [64],
  },
  {
    id: 67,
    x: 6,
    y: 36,
    points: 3,
    perks: [{ name: 'wisdom', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [62],
  },
  {
    id: 68,
    x: 1,
    y: 37,
    points: 4,
    perks: [
      { name: 'critChance', type: 'offensiveStats', value: 0.05 },
      { name: 'critEffect', type: 'offensiveStats', value: 0.1 },
    ],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [63],
  },
  {
    id: 69,
    x: 5,
    y: 37,
    points: 3,
    perks: [{ name: 'masterSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [67],
  },
  {
    id: 70,
    x: 2,
    y: 38,
    points: 3,
    perks: [
      { name: 'iceDamage', type: 'offensiveStats', value: 0.05 },
      { name: 'iceResistance', type: 'defensiveStats', value: 0.05 },
    ],
    additionalSearchKeywords: 'offenseDefense',
    prevNodesIndexes: [66],
  },
  {
    id: 71,
    x: 4,
    y: 38,
    points: 3,
    perks: [{ name: 'power', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [69],
  },
  {
    id: 72,
    x: 6,
    y: 38,
    points: 3,
    perks: [
      { name: 'darkDamage', type: 'offensiveStats', value: 0.05 },
      { name: 'darkResistance', type: 'defensiveStats', value: 0.05 },
    ],
    additionalSearchKeywords: 'offenseDefense',
    prevNodesIndexes: [67],
  },
  {
    id: 73,
    x: 3,
    y: 39,
    points: 4,
    perks: [
      { name: 'lifesteal', type: 'defensiveStats', value: 0.04 },
      {
        name: 'allDamage',
        fullNameList: ['physicalDamage', 'fireDamage', 'iceDamage', 'lightDamage', 'darkDamage'],
        type: 'offensiveStats',
        value: 0.04,
      },
    ],
    additionalSearchKeywords: 'offenseDefense',
    prevNodesIndexes: [70, 71],
  },
  {
    id: 74,
    x: 5,
    y: 39,
    points: 5,
    perks: [
      {
        name: 'earthElement',
        type: 'skills',
        description: 'earthElementDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [],
  },
  {
    id: 75,
    x: 0,
    y: 40,
    points: 3,
    perks: [{ name: 'luck', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [65, 70],
  },
  {
    id: 76,
    x: 6,
    y: 40,
    points: 3,
    perks: [{ name: 'endurance', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [72, 74],
  },
  {
    id: 77,
    x: 1,
    y: 41,
    points: 5,
    perks: [
      {
        name: 'eyeOfReincarnation',
        type: 'skills',
        description: 'eyeOfReincarnationDescription',
      },
    ],
    additionalSearchKeywords: 'activeSkill',
    prevNodesIndexes: [75],
  },
  {
    id: 78,
    x: 3,
    y: 41,
    points: 3,
    perks: [
      { name: 'fireDamage', type: 'offensiveStats', value: 0.05 },
      { name: 'fireResistance', type: 'defensiveStats', value: 0.05 },
    ],
    additionalSearchKeywords: 'offenseDefense',
    prevNodesIndexes: [73],
  },
  {
    id: 79,
    x: 5,
    y: 41,
    points: 3,
    perks: [{ name: 'wisdom', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [],
  },
  {
    id: 80,
    x: 4,
    y: 42,
    points: 4,
    perks: [
      {
        name: 'allStats',
        type: 'baseStats',
        fullNameList: ['power', 'wisdom', 'luck', 'endurance', 'agility'],
        value: 3,
      },
      { name: 'blockChance', type: 'defensiveStats', value: 0.1 },
    ],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [78, 79],
  },
  {
    id: 81,
    x: 6,
    y: 42,
    points: 5,
    perks: [
      {
        name: 'symbiosis',
        type: 'skills',
        description: 'symbiosisDescription',
      },
    ],
    additionalSearchKeywords: 'passiveSkill',
    prevNodesIndexes: [79],
  },
  {
    id: 82,
    x: 1,
    y: 43,
    points: 4,
    perks: [{ name: 'lifesteal', type: 'defensiveStats', value: 0.04 }],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [78],
  },
  {
    id: 83,
    x: 3,
    y: 43,
    points: 3,
    perks: [{ name: 'agility', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [78],
  },
  {
    id: 84,
    x: 5,
    y: 43,
    points: 3,
    perks: [{ name: 'luck', type: 'baseStats', value: 5 }],
    prevNodesIndexes: [80],
  },
  {
    id: 85,
    x: 2,
    y: 44,
    points: 4,
    perks: [
      { name: 'blockChance', type: 'defensiveStats', value: 0.05 },
      { name: 'blockEffect', type: 'defensiveStats', value: 0.1 },
    ],
    additionalSearchKeywords: 'defense',
    prevNodesIndexes: [82, 83],
  },
  {
    id: 86,
    x: 1,
    y: 45,
    points: 5,
    perks: [
      {
        name: 'breathOfWind',
        type: 'skills',
        description: 'breathOfWindDescription',
      },
    ],
    additionalSearchKeywords: 'passiveSkill',
    prevNodesIndexes: [82],
  },
  {
    id: 87,
    x: 3,
    y: 45,
    points: 5,
    perks: [
      {
        name: 'booster',
        type: 'skills',
        description: 'boosterDescription',
      },
    ],
    additionalSearchKeywords: 'passiveSkill',
    prevNodesIndexes: [84],
  },
  {
    id: 88,
    x: 5,
    y: 45,
    points: 4,
    perks: [{ name: 'cooldownRecovery', type: 'offensiveStats', value: 0.08 }],
    additionalSearchKeywords: 'offense',
    prevNodesIndexes: [84],
  },
  {
    id: 89,
    x: 4,
    y: 46,
    points: 3,
    perks: [{ name: 'masterSkillLevel', type: 'skillLvlStats', value: 2 }],
    additionalSearchKeywords: 'skillLevel',
    prevNodesIndexes: [87, 88],
  },
];
