import { NODESType } from './types';

// const getRange = (min: number, max: number, step?: number = 1) =>
//   Array.from(new Array(max > min ? Math.ceil((max - min) / step) : Math.ceil((min - max) / step)), (x, i) =>
//     max > min ? i * step + min : min - i * step
//   ).join(' | ');

export const MAX_VALUE = {
  x: 6,
  y: 48,
};

export const NODES: NODESType = [
  {
    id: 0,
    x: 2,
    y: 0,
    point: 1,
    perks: [{ name: '威', type: '属性', value: 5 }],
    prevNodesIndexes: [],
  },
  {
    id: 1,
    x: 4,
    y: 2,
    point: 2,
    perks: [{ name: '耐', type: '属性', value: 5 }],
    prevNodesIndexes: [0],
  },
  {
    id: 2,
    x: 5,
    y: 3,
    point: 2,
    perks: [{ name: '秘', type: '属性', value: 5 }],
    prevNodesIndexes: [1],
  },
  {
    id: 3,
    x: 2,
    y: 4,
    point: 2,
    perks: [{ name: '运', type: '属性', value: 5 }],
    prevNodesIndexes: [1],
  },
  {
    id: 4,
    x: 1,
    y: 5,
    point: 3,
    perks: [{ name: '全属性', type: '属性', fullNameList: ['威', '秘', '运', '耐', '敏'], value: 3 }],
    prevNodesIndexes: [3],
  },
  {
    id: 5,
    x: 3,
    y: 5,
    point: 2,
    perks: [{ name: '敏', type: '属性', value: 5 }],
    prevNodesIndexes: [2, 3],
  },
  {
    id: 6,
    x: 3,
    y: 7,
    point: 3,
    perks: [{ name: '一转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [5],
  },
  {
    id: 7,
    x: 5,
    y: 7,
    point: 3,
    perks: [{ name: '一转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [2],
  },
  {
    id: 8,
    x: 6,
    y: 8,
    point: 3,
    perks: [{ name: '运', type: '属性', value: 5 }],
    prevNodesIndexes: [7],
  },
  {
    id: 9,
    x: 1,
    y: 9,
    point: 3,
    perks: [{ name: '耐', type: '属性', value: 5 }],
    prevNodesIndexes: [6],
  },
  {
    id: 10,
    x: 3,
    y: 9,
    point: 3,
    perks: [{ name: '敏', type: '属性', value: 5 }],
    prevNodesIndexes: [6],
  },
  {
    id: 11,
    x: 5,
    y: 9,
    point: 3,
    perks: [{ name: '威', type: '属性', value: 5 }],
    prevNodesIndexes: [7],
  },
  {
    id: 12,
    x: 2,
    y: 10,
    point: 3,
    perks: [{ name: '普攻', type: '进攻属性', value: 0.07 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [9, 10],
  },
  {
    id: 13,
    x: 4,
    y: 10,
    point: 3,
    perks: [{ name: '腕力', type: '进攻属性', value: 0.5 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [11],
  },
  {
    id: 14,
    x: 6,
    y: 10,
    point: 3,
    perks: [{ name: '秘', type: '属性', value: 5 }],
    prevNodesIndexes: [8],
  },
  {
    id: 15,
    x: 1,
    y: 13,
    point: 4,
    perks: [{ name: '燃烧间隔减50%', type: '特殊' }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [9],
  },
  {
    id: 16,
    x: 3,
    y: 13,
    point: 3,
    perks: [{ name: '二转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [14],
  },
  {
    id: 17,
    x: 2,
    y: 14,
    point: 3,
    perks: [{ name: '全抗', type: '防御属性', fullNameList: ['物抗', '火抗', '冰抗', '光抗', '暗抗'], value: 0.04 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [],
  },
  {
    id: 18,
    x: 1,
    y: 15,
    point: 3,
    perks: [{ name: '二转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [15, 17],
  },
  {
    id: 19,
    x: 3,
    y: 15,
    point: 3,
    perks: [{ name: '全属性', type: '属性', fullNameList: ['威', '秘', '运', '耐', '敏'], value: 3 }],
    prevNodesIndexes: [16],
  },
  {
    id: 20,
    x: 0,
    y: 16,
    point: 5,
    perks: [
      {
        name: '生命绽放',
        type: '技能',
        description: '使角色持续5秒每秒恢复生命，持续时间内受到的伤害降低40%。\n每秒恢复：角色攻击57.4%点生命值。',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [18],
  },
  {
    id: 21,
    x: 2,
    y: 16,
    point: 3,
    perks: [{ name: '暴击率', type: '进攻属性', value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [17, 19],
  },
  {
    id: 22,
    x: 1,
    y: 17,
    point: 3,
    perks: [{ name: '威', type: '属性', value: 5 }],
    prevNodesIndexes: [20],
  },
  {
    id: 23,
    x: 5,
    y: 17,
    point: 3,
    perks: [{ name: '一转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [],
  },
  {
    id: 24,
    x: 2,
    y: 18,
    point: 3,
    perks: [{ name: '秘', type: '属性', value: 5 }],
    prevNodesIndexes: [22],
  },
  {
    id: 25,
    x: 6,
    y: 18,
    point: 4,
    perks: [{ name: '中毒效果翻倍', type: '特殊' }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [],
  },
  {
    id: 26,
    x: 1,
    y: 19,
    point: 5,
    perks: [
      {
        name: '灵魂射线',
        type: '技能',
        description:
          '随机对多个目标进行攻击，造成暗属性伤害，距离越远攻击目标越多。\n暗属性伤害：主手基础伤害205.0%+315点',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [],
  },
  {
    id: 27,
    x: 5,
    y: 19,
    point: 3,
    perks: [{ name: '敏', type: '属性', value: 5 }],
    prevNodesIndexes: [21, 23, 25],
  },
  {
    id: 28,
    x: 0,
    y: 20,
    point: 3,
    perks: [{ name: '暗伤', type: '进攻属性', value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [26],
  },
  {
    id: 29,
    x: 2,
    y: 20,
    point: 3,
    perks: [{ name: '全属性', type: '属性', fullNameList: ['威', '秘', '运', '耐', '敏'], value: 3 }],
    prevNodesIndexes: [24, 26],
  },
  {
    id: 30,
    x: 1,
    y: 21,
    point: 3,
    perks: [{ name: '全伤', type: '进攻属性', fullNameList: ['物伤', '火伤', '冰伤', '光伤', '暗伤'], value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [28, 29],
  },
  {
    id: 31,
    x: 3,
    y: 21,
    point: 3,
    perks: [{ name: '运', type: '属性', value: 5 }],
    prevNodesIndexes: [29],
  },
  {
    id: 32,
    x: 5,
    y: 21,
    point: 5,
    perks: [
      {
        name: '混元盾',
        type: '技能',
        description: '角色立即获得护盾，还将获得1层圣盾，圣盾可抵挡1次攻击。\n护盾：相当于生命上限的8.6%。',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [27],
  },
  {
    id: 33,
    x: 4,
    y: 22,
    point: 3,
    perks: [{ name: '生命吸取', type: '防御属性', value: 0.04 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [31],
  },
  {
    id: 34,
    x: 1,
    y: 23,
    point: 3,
    perks: [{ name: '攻速', type: '进攻属性', value: 0.1 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [30],
  },
  {
    id: 35,
    x: 3,
    y: 23,
    point: 3,
    perks: [{ name: '普攻', type: '进攻属性', value: 0.07 }],
    prevNodesIndexes: [33],
  },
  {
    id: 36,
    x: 5,
    y: 23,
    point: 3,
    perks: [{ name: '耐', type: '属性', value: 5 }],
    prevNodesIndexes: [32, 33],
  },
  {
    id: 37,
    x: 0,
    y: 24,
    point: 4,
    perks: [{ name: '流血效果翻倍', type: '特殊' }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [34],
  },
  {
    id: 38,
    x: 4,
    y: 24,
    point: 3,
    perks: [{ name: '格挡率', type: '防御属性', value: 0.05 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [35, 36],
  },
  {
    id: 39,
    x: 6,
    y: 24,
    point: 3,
    perks: [{ name: '二转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [36],
  },
  {
    id: 40,
    x: 1,
    y: 25,
    point: 3,
    perks: [{ name: '火伤', type: '进攻属性', value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [34],
  },
  {
    id: 41,
    x: 0,
    y: 26,
    point: 3,
    perks: [{ name: '物伤', type: '进攻属性', value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [37],
  },
  {
    id: 42,
    x: 2,
    y: 26,
    point: 3,
    perks: [{ name: '生命', type: '防御属性', value: 0.05 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [40],
  },
  {
    id: 43,
    x: 4,
    y: 26,
    point: 5,
    perks: [
      {
        name: '超重击',
        type: '技能',
        description:
          '对3目标进行攻击，造成物理伤害；超重击冷却时间受主武器影响。\n物理伤害：主手基础伤害133.3%+205点。',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [38],
  },
  {
    id: 44,
    x: 6,
    y: 26,
    point: 5,
    perks: [
      {
        name: '水元素',
        type: '技能',
        description: '身前召唤，水元素普攻对单体造成冰属性伤害。\n冰属性伤害：自身基础伤害307.5%+473点。',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [],
  },
  {
    id: 45,
    x: 1,
    y: 27,
    point: 5,
    perks: [
      {
        name: '天体陨落',
        type: '技能',
        description:
          '触发陨石效果：每波随机2个目标降下流星，1秒内总计4波，每颗流星造成或属性伤害。\n火属性伤害：主手基础伤害153.8%+236点。',
      },
    ],

    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [41, 42],
  },
  {
    id: 46,
    x: 2,
    y: 28,
    point: 3,
    perks: [{ name: '三转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [45],
  },
  {
    id: 47,
    x: 4,
    y: 28,
    point: 3,
    perks: [
      { name: '攻击', type: '进攻属性', value: 0.05 },
      { name: '召唤增幅', type: '进攻属性', value: 0.05 },
    ],
    prevNodesIndexes: [43],
    AdditionalSearchKeywords: '进攻',
  },
  {
    id: 48,
    x: 6,
    y: 28,
    point: 3,
    perks: [{ name: '暴击效果', type: '进攻属性', value: 0.1 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [44],
  },
  {
    id: 49,
    x: 3,
    y: 29,
    point: 5,
    perks: [
      { name: '胜利鼓舞', type: '技能', description: '战斗中任意敌方目标重伤后，恢复角色生命。\n恢复：5.5%的生命。' },
    ],
    AdditionalSearchKeywords: '被动技能',
    prevNodesIndexes: [46, 47],
  },
  {
    id: 50,
    x: 5,
    y: 29,
    point: 3,
    perks: [{ name: '三转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [47, 48],
  },
  {
    id: 51,
    x: 4,
    y: 30,
    point: 3,
    perks: [{ name: '光伤', type: '进攻属性', value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [49, 50],
  },
  {
    id: 52,
    x: 1,
    y: 31,
    point: 3,
    perks: [{ name: '耐', type: '属性', value: 5 }],
    prevNodesIndexes: [49],
  },
  {
    id: 53,
    x: 3,
    y: 31,
    point: 4,
    perks: [{ name: '全抗', type: '防御属性', fullNameList: ['物抗', '火抗', '冰抗', '光抗', '暗抗'], value: 0.08 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [],
  },
  {
    id: 54,
    x: 5,
    y: 31,
    point: 3,
    perks: [{ name: '敏', type: '属性', value: 5 }],
    prevNodesIndexes: [50],
  },
  {
    id: 55,
    x: 0,
    y: 32,
    point: 3,
    perks: [{ name: '冰伤', type: '进攻属性', value: 0.05 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [52],
  },
  {
    id: 56,
    x: 4,
    y: 32,
    point: 3,
    perks: [{ name: '护甲', type: '防御属性', value: 0.05 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [53, 54],
  },
  {
    id: 57,
    x: 1,
    y: 33,
    point: 5,
    perks: [
      {
        name: '链钩',
        type: '技能',
        description:
          '对2目标进行攻击，偷袭造成物理伤害，拉近距离3，是目标附带1层流血。\n物理伤害：主手基础伤害184.5%+284点。',
      },
    ],

    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [52, 55],
  },
  {
    id: 58,
    x: 3,
    y: 33,
    point: 5,
    perks: [
      {
        name: '净世之光',
        type: '技能',
        description: '对敌方全体进行攻击，造成光属性伤害。\n光属性伤害：主手基础伤害307.5%+473点。',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [],
  },
  {
    id: 59,
    x: 5,
    y: 33,
    point: 3,
    perks: [{ name: '威', type: '属性', value: 5 }],
    prevNodesIndexes: [],
  },
  {
    id: 60,
    x: 2,
    y: 34,
    point: 3,
    perks: [
      { name: '光伤', type: '进攻属性', value: 0.05 },
      { name: '光抗', type: '防御属性', value: 0.05 },
    ],
    AdditionalSearchKeywords: '进攻 防御',
    prevNodesIndexes: [58],
  },
  {
    id: 61,
    x: 4,
    y: 34,
    point: 3,
    perks: [{ name: '三转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [59],
  },
  {
    id: 62,
    x: 6,
    y: 34,
    point: 4,
    perks: [{ name: '随从攻速', type: '进攻属性', value: 0.1 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [48, 59],
  },
  {
    id: 63,
    x: 1,
    y: 35,
    point: 3,
    perks: [
      { name: '物伤', type: '进攻属性', value: 0.05 },
      { name: '物抗', type: '防御属性', value: 0.05 },
    ],
    AdditionalSearchKeywords: '进攻 防御',
    prevNodesIndexes: [57],
  },
  {
    id: 64,
    x: 3,
    y: 35,
    point: 4,
    perks: [{ name: '绝闪', type: '防御属性', value: 0.08 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [60, 61],
  },
  {
    id: 65,
    x: 0,
    y: 36,
    point: 3,
    perks: [{ name: '四转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [63],
  },
  {
    id: 66,
    x: 2,
    y: 36,
    point: 3,
    perks: [{ name: '全属性', type: '属性', fullNameList: ['威', '秘', '运', '耐', '敏'], value: 3 }],
    prevNodesIndexes: [64],
  },
  {
    id: 67,
    x: 6,
    y: 36,
    point: 3,
    perks: [{ name: '秘', type: '属性', value: 5 }],
    prevNodesIndexes: [62],
  },
  {
    id: 68,
    x: 1,
    y: 37,
    point: 4,
    perks: [
      { name: '暴击率', type: '进攻属性', value: 0.05 },
      { name: '暴击效果', type: '进攻属性', value: 0.1 },
    ],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [63],
  },
  {
    id: 69,
    x: 5,
    y: 37,
    point: 3,
    perks: [{ name: '四转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [67],
  },
  {
    id: 70,
    x: 2,
    y: 38,
    point: 3,
    perks: [
      { name: '冰伤', type: '进攻属性', value: 0.05 },
      { name: '冰抗', type: '防御属性', value: 0.05 },
    ],
    AdditionalSearchKeywords: '进攻 防御',
    prevNodesIndexes: [66],
  },
  {
    id: 71,
    x: 4,
    y: 38,
    point: 3,
    perks: [{ name: '威', type: '属性', value: 5 }],
    prevNodesIndexes: [69],
  },
  {
    id: 72,
    x: 6,
    y: 38,
    point: 3,
    perks: [
      { name: '暗伤', type: '进攻属性', value: 0.05 },
      { name: '暗抗', type: '防御属性', value: 0.05 },
    ],
    AdditionalSearchKeywords: '进攻 防御',
    prevNodesIndexes: [67],
  },
  {
    id: 73,
    x: 3,
    y: 39,
    point: 4,
    perks: [
      { name: '生命吸取', type: '防御属性', value: 0.04 },
      { name: '全伤', fullNameList: ['物伤', '火伤', '冰伤', '光伤', '暗伤'], type: '进攻属性', value: 0.04 },
    ],
    AdditionalSearchKeywords: '进攻 防御',
    prevNodesIndexes: [70, 71],
  },
  {
    id: 74,
    x: 5,
    y: 39,
    point: 5,
    perks: [
      {
        name: '土元素',
        type: '技能',
        description: '身后召唤，土元素普攻对单体造成物理伤害，击退距离2.\n物理伤害：土元素基础伤害422.3%+649点。',
      },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [],
  },
  {
    id: 75,
    x: 0,
    y: 40,
    point: 3,
    perks: [{ name: '运', type: '属性', value: 5 }],
    prevNodesIndexes: [65, 70],
  },
  {
    id: 76,
    x: 6,
    y: 40,
    point: 3,
    perks: [{ name: '耐', type: '属性', value: 5 }],
    prevNodesIndexes: [72, 74],
  },
  {
    id: 77,
    x: 1,
    y: 41,
    point: 5,
    perks: [
      { name: '轮回眼', type: '技能', description: '间隔一段时间，复制前一个角色使用的技能。\n间隔时间：34秒。' },
    ],
    AdditionalSearchKeywords: '主动技能',
    prevNodesIndexes: [75],
  },
  {
    id: 78,
    x: 3,
    y: 41,
    point: 3,
    perks: [
      { name: '火伤', type: '进攻属性', value: 0.05 },
      { name: '火抗', type: '防御属性', value: 0.05 },
    ],
    AdditionalSearchKeywords: '进攻 防御',
    prevNodesIndexes: [73],
  },
  {
    id: 79,
    x: 5,
    y: 41,
    point: 3,
    perks: [{ name: '秘', type: '属性', value: 5 }],
    prevNodesIndexes: [],
  },
  {
    id: 80,
    x: 4,
    y: 42,
    point: 4,
    perks: [
      { name: '全属性', type: '属性', fullNameList: ['威', '秘', '运', '耐', '敏'], value: 3 },
      { name: '格挡率', type: '防御属性', value: 0.1 },
    ],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [78, 79],
  },
  {
    id: 81,
    x: 6,
    y: 42,
    point: 5,
    perks: [
      { name: '共生', type: '技能', description: '友方有任意随从存活时，则角色受到的伤害降低。\n伤害降低：11.0%。' },
    ],
    AdditionalSearchKeywords: '被动技能',
    prevNodesIndexes: [79],
  },
  {
    id: 82,
    x: 1,
    y: 43,
    point: 4,
    perks: [{ name: '生命吸取', type: '防御属性', value: 0.04 }],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [78],
  },
  {
    id: 83,
    x: 3,
    y: 43,
    point: 3,
    perks: [{ name: '敏', type: '属性', value: 5 }],
    prevNodesIndexes: [78],
  },
  {
    id: 84,
    x: 5,
    y: 43,
    point: 3,
    perks: [{ name: '运', type: '属性', value: 5 }],
    prevNodesIndexes: [80],
  },
  {
    id: 85,
    x: 2,
    y: 44,
    point: 4,
    perks: [
      { name: '格挡率', type: '防御属性', value: 0.05 },
      { name: '格挡效果', type: '防御属性', value: 0.1 },
    ],
    AdditionalSearchKeywords: '防御',
    prevNodesIndexes: [82, 83],
  },
  {
    id: 86,
    x: 1,
    y: 45,
    point: 5,
    perks: [
      {
        name: '风息',
        type: '技能',
        description:
          '角色武器普攻有20%的概率触发风息效果：对目标造成真实伤害，手角色普攻伤害加成影响。\n真实伤害：主手攻击34.1%+96点。',
      },
    ],
    AdditionalSearchKeywords: '被动技能',
    prevNodesIndexes: [82],
  },
  {
    id: 87,
    x: 3,
    y: 45,
    point: 5,
    perks: [
      {
        name: '技能振幅',
        type: '技能',
        description: '角色每次使用攻击技能后，使角色伤害提高1.5%，可叠加。\n叠加次数：11次。',
      },
    ],
    AdditionalSearchKeywords: '被动技能',
    prevNodesIndexes: [84],
  },
  {
    id: 88,
    x: 5,
    y: 45,
    point: 4,
    perks: [{ name: '冷却恢复', type: '进攻属性', value: 0.08 }],
    AdditionalSearchKeywords: '进攻',
    prevNodesIndexes: [84],
  },
  {
    id: 89,
    x: 4,
    y: 46,
    point: 3,
    perks: [{ name: '四转', type: '技能等级属性', value: 2 }],
    AdditionalSearchKeywords: '技能等级',
    prevNodesIndexes: [87, 88],
  },
];
